name: uwasa

on:
  push:
    branches:
      - master
  schedule:
    - cron: '2,9,18,36,54 * * * *'

permissions:
  contents: write

jobs:
  uwasa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Uwasa
        id: uwasa
        run: bun uwasa.mjs
        env:
          UWASA_GH_TOKEN: ${{ secrets.UWASA_GH_TOKEN }}
          UWASA_ANNOUNCEMENTS: ${{ secrets.UWASA_ANNOUNCEMENTS }}
          UWASA_AVATAR: ${{ secrets.UWASA_AVATAR }}
          UWASA_NAME: ${{ secrets.UWASA_NAME }}
          UWASA_ORIGINS: ${{ secrets.UWASA_ORIGINS }}
          UWASA_WEBHOOK: ${{ secrets.UWASA_WEBHOOK }}
          UWASA_RE_MAINTENANCE: ${{ secrets.UWASA_RE_MAINTENANCE }}
          UWASA_RE_APPVERSION: ${{ secrets.UWASA_RE_APPVERSION }}
          UWASA_RE_MAGIREPO: ${{ secrets.UWASA_RE_MAGIREPO }}
          UWASA_LAST: ${{ vars.LAST }}
          UWASA_ETAG: ${{ vars.ETAG }}
      - name: Update announcements
        run: |
          git config --global user.name 'Uwasa'
          git config --global user.email 'uwasa@cirno.name'
          git commit -a -m "update announcements" && git push || true
