name: uwasa

on:
  schedule:
    - cron: '2,9,18,36 * * * *'

permissions:
  contents: write

jobs:
  uwasa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Uwasa
        id: uwasa
        run: bun uwasa.mjs
        env:
          UWASA_ORIGIN: ${{ secrets.UWASA_ORIGIN }}
          UWASA_ANNOUNCEMENTS: ${{ secrets.UWASA_ANNOUNCEMENTS }}
          UWASA_WEBHOOK: ${{ secrets.UWASA_WEBHOOK }}
      - name: Update announcements
        run: |
          git config --global user.name 'Uwasa'
          git config --global user.email 'uwasa@cirno.name'
          git commit -a -m "update announcements"
          git push || true
