name: uwasa

on:
  schedule:
    - cron: '2/9 * * * *'

permissions:
  contents: write

jobs:
  uwasa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Uwasa
        run: bun uwasa.mjs
        env:
          UWASA_GH_TOKEN: ${{ secrets.UWASA_GH_TOKEN }}
          UWASA_ANNOUNCEMENTS: ${{ secrets.UWASA_ANNOUNCEMENTS }}
          UWASA_AVATAR: ${{ secrets.UWASA_AVATAR }}
          UWASA_NAME: ${{ secrets.UWASA_NAME }}
          UWASA_ORIGINS: ${{ secrets.UWASA_ORIGINS }}
          UWASA_WEBHOOK: ${{ secrets.UWASA_WEBHOOK }}
          UWASA_RE_MAINTENANCE: ${{ secrets.UWASA_RE_MAINTENANCE }}
          UWASA_RE_APPVERSION: ${{ secrets.UWASA_RE_APPVERSION }}
          UWASA_RE_MAGIREPO: ${{ secrets.UWASA_RE_MAGIREPO }}
          UWASA_LAST: ${{ vars.LAST }}
          UWASA_ETAG: ${{ vars.ETAG }}
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update announcements
          file_pattern: 'announcements/*.json'
          commit_user_name: Uwasa
          commit_user_email: uwasa@cirno.name
